version: '3.8'
services:
  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-docker-compose
    ports:
      - 3000:3000
    volumes:
      - './frontend:/usr/app'
      - './usr/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-docker-compose
    ports:
      - 4000:4000
    volumes:
      - './backend:/usr/app'
      - './usr/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
